### ISSUE TITLE
Installation version 1.2.1 with CocoaPods

### ISSUE THREAD

**Issue by DnV1eX** [wtw-software/UTMConversion#8]
After update pod from version 1.2.0 to 1.2.1 getting compile error:
> 'UTMConversion.h' file not found

**Comment by peterringset** [comment]
Can you give a little bit more info about your error? For me it compiles fine with an empty Xcode project. What version of Xcode are you using? What version of Swift?

**Comment by peterringset** [comment]
Closing this one, let me know it the problem continues
